CREATE DATABASE IF NOT EXISTS MarkovDB;
use `MarkovDB`;

CREATE TABLE IF NOT EXISTS chain (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link1 VARCHAR(512),
    link2 VARCHAR(512),
    n INT
);
